### ISSUE TITLE
Issue with Output epub

### ISSUE THREAD

**Issue by UPSA007** [binarynonsense/comic-book-reader#28]
No eBook editor or reader can open the output epub file. It always shows an error.
Sigil Error Message
Error info: Cannot load file C:\Users\upama\OneDrive\Desktop\New folder\New folder\Daytripper #1 (of 10) - Fabio Moon & Gabriel Ba.epub: C:/Users/upama/AppData/Local/sigil-ebook/sigil/workspace/Sigil-HWNmhj/META-INF/container.xml: Epub has missing or improperly specified OPF.
Sigil version: 1.9.30
Runtime Qt: 5.12.9
Compiled Qt: 5.12.9
System: Windows 10 (10.0)
Architecture: x86_64

Calibre eBook Editor Error Messege
calibre, version 6.19.1
ERROR: Loading book failed: Failed to open the book at C:\Users\upama\OneDrive\Desktop\New folder\New folder\Daytripper #1 (of 10) - Fabio Moon & Gabriel Ba.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\upama\OneDrive\Desktop\New folder\New folder\Daytripper #1 (of 10) - Fabio Moon & Gabriel Ba.epub with error:
Traceback (most recent call last):
  File "calibre\ebooks\metadata\epub.py", line 98, in __init__
  File "calibre\ebooks\metadata\epub.py", line 152, in open
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'META-INF/container.xml' in the archive"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 175, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 237, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 216, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 164, in get_zip_reader
  File "calibre\ebooks\metadata\epub.py", line 147, in __init__
  File "calibre\ebooks\metadata\epub.py", line 101, in __init__
calibre.ebooks.metadata.epub.EPubException: missing OCF container.xml file
WARNING: Epub doesn't contain a valid mimetype declaration
InputFormatPlugin: EPUB Input running
on C:\Users\upama\AppData\Local\Temp\calibre_xf40kep9\k_occkdt.epub
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 238, in find_opf
FileNotFoundError: [Errno 2] No such file or directory: 'META-INF/container.xml'
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 826, in viewer_main
  File "calibre\srv\render_book.py", line 817, in render_for_viewer
  File "calibre\srv\render_book.py", line 794, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 278, in convert
ValueError: C:\Users\upama\AppData\Local\Temp\calibre_xf40kep9\k_occkdt.epub is not a valid EPUB file (could not find opf)

**Comment by binarynonsense** [comment]
Thanks for the bug report! You are right, looks like epub generation has been broken for a while and I didn't notice during my usual testing :(

I'll try to fix it as soon as I have the time but, meanwhile, seems like [version 2.2.1](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.2.1) is the last one where it properly works, in case you need to make a conversion to epub.

**Comment by UPSA007** [comment]
Thank You for you prompt attention.
